[workspace]
members = [
    "emsdk",
    "examples/amm",
    "examples/simple_multiply",
    "examples/calculator_rational",
    "examples/calculator_fractional",
    "examples/chi_sq",
    "examples/dot_prod",
    "examples/pir",
    "seal",
    "seal_bench",
    "sunscreen",
    "sunscreen_backend",
    "sunscreen_compiler_macros",
    "sunscreen_fhe_program",
    "sunscreen_runtime",
]
