[workspace]
members = [
    "emsdk",
    "examples/simple_multiply",
    "examples/calculator",
    "seal",
    "seal_bench",
    "sunscreen_backend",
    "sunscreen_compiler",
    "sunscreen_compiler_macros",
    "sunscreen_circuit",
    "sunscreen_runtime",
]
