[package]
name = "sunscreen_frontend_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.0"
sunscreen_circuit = { path = "../sunscreen_circuit" }