[package]
name = "sunscreen_math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
metal = { version = "0.24.0", optional = true }
rand = "0.8.5"
curve25519_dalek = { package = "sunscreen_curve25519", path = "../sunscreen_curve25519", features = ["serde", "u64_backend"], default-features = false }
rayon = "1.6.1"
tokio = { version = "1.25.0", features = ["rt"], optional = true }
wgpu = { version = "0.15.1", optional = true }

[features]
default = ["webgpu"]
nightly-features = []
metal = ["dep:metal", "gpu"]
webgpu = ["dep:wgpu", "dep:tokio", "gpu"]
gpu = []
pina = []