[package]
name = "sunscreen"
# Read and understand
# https://doc.rust-lang.org/cargo/reference/semver.html
# before bumping the version.
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = "3.8.0"
clap = "2.34.0"
log = "0.4.14"
num = "0.4.0"
petgraph = "0.6.0"
sunscreen_compiler_macros = { version = "0.5", path = "../sunscreen_compiler_macros", registry = "sunscreen"  }
sunscreen_backend = { version = "0.5", path = "../sunscreen_backend", registry = "sunscreen"  }
sunscreen_fhe_program = { version = "0.5", path = "../sunscreen_fhe_program", registry = "sunscreen"  }
sunscreen_runtime = { version = "0.5", path = "../sunscreen_runtime", registry = "sunscreen"  }
seal_fhe = { version = "0.5", path = "../seal_fhe", registry = "sunscreen" }
serde = { version = "1.0.130", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.72"
float-cmp = "0.9.0"

[features]
hexl = ["seal_fhe/hexl"]