[package]
name = "sunscreen_fhe_program"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = { version = "0.6.0", features = ["serde-1"] }
serde = { version = "1.0.130", features = ["derive"] }
seal_fhe = { version = "0.4", path = "../seal_fhe", registry = "sunscreen" }

[dev-dependencies]
serde_json = "1.0.71"