name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: CPU Features
      run: cat /proc/cpuinfo
    - name: Format
      run: cargo fmt --check
    - name: Build and run tests
      run: cargo test --verbose --release
    - name: Verify amm
      run: cargo run --release --bin amm
      
