name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: CPU Features
      run: cat /proc/cpuinfo
    - name: Format
      run: cargo fmt --check
    - name: Build and run tests
      run: cargo test --verbose --release
    - name: Verify examples (amm)
      run: cargo run --release --bin amm
    - name: Verify examples (chi_sq)
      run: cargo run --release --bin chi_sq
    - name: Verify examples (simple_multiply)
      run: cargo run --release --bin simple_multiply
    - name: Verify examples (dot_prod)
      run: cargo run --release --bin dot_prod
    - name: Verify examples (pir)
      run: cargo run --release --bin pir
      
