[package]
name = "sunscreen_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seal = { path = "../seal" }
sunscreen_ir = { path = "../sunscreen_ir" }
sunscreen_runtime = { path = "../sunscreen_runtime" }
petgraph = "0.6.0"