[package]
name = "sunscreen_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seal = { version = "^0.1", path = "../seal", registry = "sunscreen"  }
sunscreen_fhe_program = { version = "^0.1", path = "../sunscreen_fhe_program", registry = "sunscreen"  }
sunscreen_runtime = { version = "^0.1", path = "../sunscreen_runtime", registry = "sunscreen"  }
petgraph = "0.6.0"
log = "0.4.14"
env_logger = "0.9.0"