[package]
name = "sunscreen_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seal = { path = "../seal" }
sunscreen_circuit = { path = "../sunscreen_circuit" }
sunscreen_runtime = { path = "../sunscreen_runtime" }
petgraph = "0.6.0"
log = "0.4.14"
env_logger = "0.9.0"