[package]
name = "sunscreen_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.1"
seal = { path = "../seal" }
sunscreen_circuit = { path = "../sunscreen_circuit" }
petgraph = "0.6.0"
num_cpus = "1.13.0"
scoped_threadpool = "0.1.9"