[package]
name = "sunscreen_runtime"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
crossbeam = "0.8.1"
log = "0.4.14"
seal_fhe = { version = "0.5", path = "../seal_fhe", registry = "sunscreen" }
sunscreen_fhe_program = { version = "0.5", path = "../sunscreen_fhe_program", registry = "sunscreen"  }
petgraph = "0.6.0"
num_cpus = "1.13.0"
rayon = "1.5.1"
rlp = "0.5.1"
serde = "1.0.130"
semver = "1.0.4"

[dev-dependencies]
serde_json = "1.0.74"
sunscreen = { path = "../sunscreen" }